library(Seurat)

load("/home/ytanaka/scratch/mouse_midbrain_v15/human.integrated.dat")
OL_human <- subset(human.integrated, subset = CellType == 2)
OPC_human <- subset(human.integrated, subset = CellType == 3)
AS_human <- subset(human.integrated, subset = CellType == 4)
MG_human <- subset(human.integrated, subset = CellType == 6)
OL_OPC_human <- subset(human.integrated, subset = CellType == 2 | CellType == 3)

OL_human <- SCTransform(OL_human, vars.to.regress=c("percent.mito"))
OL_human <- RunPCA(OL_human)
OL_human <- RunUMAP(OL_human,dims=1:10)
OL_human <- FindNeighbors(OL_human, reduction = "pca", dims = 1:10)
OL_human <- FindClusters(OL_human)

OPC_human <- SCTransform(OPC_human, vars.to.regress=c("percent.mito"))
OPC_human <- RunPCA(OPC_human)
OPC_human <- RunUMAP(OPC_human,dims=1:10)
OPC_human <- FindNeighbors(OPC_human, reduction = "pca", dims = 1:10)
OPC_human <- FindClusters(OPC_human)

MG_human <- SCTransform(MG_human, vars.to.regress=c("percent.mito"))
MG_human <- RunPCA(MG_human)
MG_human <- RunUMAP(MG_human,dims=1:10)
MG_human <- FindNeighbors(MG_human, reduction = "pca", dims = 1:10)
MG_human <- FindClusters(MG_human)

AS_human <- SCTransform(AS_human, vars.to.regress=c("percent.mito"))
AS_human <- RunPCA(AS_human)
AS_human <- RunUMAP(AS_human,dims=1:10)
AS_human <- FindNeighbors(AS_human, reduction = "pca", dims = 1:10)
AS_human <- FindClusters(AS_human)

OL_OPC_human <- SCTransform(OL_OPC_human, vars.to.regress=c("percent.mito"))
OL_OPC_human <- RunPCA(OL_OPC_human)
OL_OPC_human <- RunUMAP(OL_OPC_human,dims=1:10)
OL_OPC_human <- FindNeighbors(OL_OPC_human, reduction = "pca", dims = 1:10)
OL_OPC_human <- FindClusters(OL_OPC_human)

save(OL_human,file="OL_human.dat")
save(OPC_human,file="OPC_human.dat")
save(AS_human,file="AS_human.dat")
save(MG_human,file="MG_human.dat")
save(OL_OPC_human,file="OL_OPC_human.dat")

load("/home/ytanaka/scratch/mouse_midbrain_v15/mouse.integrated.dat")
OL_mouse <- subset(mouse.integrated, subset = CellType == 2)
OPC_mouse <- subset(mouse.integrated, subset = CellType == 3)
AS_mouse <- subset(mouse.integrated, subset = CellType == 4)
MG_mouse <- subset(mouse.integrated, subset = CellType == 6)
OL_OPC_mouse <-	subset(mouse.integrated, subset = CellType == 2 | CellType == 3)

OL_mouse <- SCTransform(OL_mouse, vars.to.regress=c("percent.mito"))
OL_mouse <- RunPCA(OL_mouse)
OL_mouse <- RunUMAP(OL_mouse,dims=1:10)
OL_mouse <- FindNeighbors(OL_mouse, reduction = "pca", dims = 1:10)
OL_mouse <- FindClusters(OL_mouse)

OPC_mouse <- SCTransform(OPC_mouse, vars.to.regress=c("percent.mito"))
OPC_mouse <- RunPCA(OPC_mouse)
OPC_mouse <- RunUMAP(OPC_mouse,dims=1:10)
OPC_mouse <- FindNeighbors(OPC_mouse, reduction = "pca", dims = 1:10)
OPC_mouse <- FindClusters(OPC_mouse)

MG_mouse <- SCTransform(MG_mouse, vars.to.regress=c("percent.mito"))
MG_mouse <- RunPCA(MG_mouse)
MG_mouse <- RunUMAP(MG_mouse,dims=1:10)
MG_mouse <- FindNeighbors(MG_mouse, reduction = "pca", dims = 1:10)
MG_mouse <- FindClusters(MG_mouse)

AS_mouse <- SCTransform(AS_mouse, vars.to.regress=c("percent.mito"))
AS_mouse <- RunPCA(AS_mouse)
AS_mouse <- RunUMAP(AS_mouse,dims=1:10)
AS_mouse <- FindNeighbors(AS_mouse, reduction = "pca", dims = 1:10)
AS_mouse <- FindClusters(AS_mouse)

OL_OPC_mouse <- SCTransform(OL_OPC_mouse, vars.to.regress=c("percent.mito"))
OL_OPC_mouse <- RunPCA(OL_OPC_mouse)
OL_OPC_mouse <- RunUMAP(OL_OPC_mouse,dims=1:10)
OL_OPC_mouse <- FindNeighbors(OL_OPC_mouse, reduction = "pca", dims = 1:10)
OL_OPC_mouse <- FindClusters(OL_OPC_mouse)

save(OL_mouse,file="OL_mouse.dat")
save(OPC_mouse,file="OPC_mouse.dat")
save(AS_mouse,file="AS_mouse.dat")
save(MG_mouse,file="MG_mouse.dat")
save(OL_OPC_mouse,file="OL_OPC_mouse.dat")